name: Publish Blog via GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy Hexo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Deploy docs
        uses: aiokr/deploy-ghpages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The repository the action should deploy to.
          PUBLISH_REPOSITORY: aiokr/Theme-Type-Starter-Kit
          # The branch the action should deploy to.
          BRANCH: gh-pages
